
title: Reason I Think
author: Eden Harris
email: aussiedwarf@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is a place for me to work out what is reasonable and rational
baseurl: ""
twitter_username: aussiedwarf
github_username:  aussiedwarf

# Build settings
markdown: kramdown
highlighter: rouge
  
sass:
    sass_dir: _sass
